# Generated by Django 5.2.3 on 2025-06-14 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_monthlybudget_month_monthlybudget_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
